SELECT * FROM cust.shop;

-- What is the total revenue generated by male vs female customers?
SELECT gender,SUM(purchase_amount) AS revenue
FROM shop
GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM shop
WHERE subscription_status = 'Yes' AND
purchase_amount > (SELECT AVG(purchase_amount) 
				   FROM shop);

-- Which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating),2) AS avg_rating 
FROM shop
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, 
ROUND(AVG(purchase_amount),2) AS avg_amt
FROM shop
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
SUM(purchase_amount) AS total_revenue 
FROM shop
GROUP BY subscription_status;

-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100)/COUNT(*),2) AS discount_rate
FROM shop
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH cust_type AS(SELECT customer_id,
				  previous_purchases,
				  CASE WHEN previous_purchases = 1 THEN 'New'
					   WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
					   WHEN previous_purchases > 10 THEN 'Loyal'
				  END AS Segment
			      FROM shop)

SELECT Segment, 
COUNT(customer_id) AS 'total_customers'
FROM cust_type
GROUP BY Segment;

-- What are the top 3 most purchased products within each category?
WITH rank_of_item AS (SELECT category,item_purchased,
					  COUNT(item_purchased) AS total_units,
					  ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS item_rank
				      FROM shop
					  GROUP BY category,item_purchased)
                      
SELECT * 
FROM rank_of_item
WHERE item_rank<4;                      
                      
-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(*) AS repeat_buyers
FROM shop
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group?
SELECT age_group, 
SUM(purchase_amount) AS revenue
FROM shop
GROUP BY age_group
ORDER BY revenue DESC;
 